name: Factory CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Factory
      run: docker compose up -d --build

    - name: Wait for systems to initialize
      run: sleep 80

    - name: Run Pytest
      run: docker compose exec -T api pytest

    - name: Run Linter (Flake8)
      run: |
        docker compose exec -T api pip install flake8
        docker compose exec -T api flake8 . --count --select=E9,F63,F7,F82,F401 --show-source --statistics